### ISSUE TITLE
quemu-system-x86_64: -audiodev: invalid option

### ISSUE THREAD

**Issue by laTruffe79** [arindas/mac-on-linux-with-qemu#13]
Hello, 
launching mac on linux fails with the error quemu-system-x86_64: -audiodev: invalid option on debian 10.

**Comment by arindas** [comment]
Related threads
https://www.reddit.com/r/debian/comments/kmje3i/qemu_from_busterbackports_and_audiodev/
https://ubuntu-mate.community/t/unable-to-run-quickemu-audiodev-invalid-option-error/23715

Suggested fix:
Install the packages qemu-system-common and qemu-system-gui if available. Ensure you are using the latest packages.

With the percentage of people having problems with qemu packages, I might have to bundle a build of qemu along with the scripts. The idea is to create an AppImage later on to avoid platform specific problems. Till then all I can request is to research a bit about the problems that frequently occur with qemu on your distribution.
