### ISSUE TITLE
why big sur update cannot be completed ? 

### ISSUE THREAD

**Issue by tombombadilom** [arindas/mac-on-linux-with-qemu#15]
Big sur upgrade is proposed , downloaded and the first step install completed. 
But after reboot, it is as if nothing had happend and the system reboot as catalina os.
Same thing for the last 2021-04 security update.
I tried to change the external update process back to normal but no result.

Is it possible to change the fetch-macos.py script instead and  change the https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog ,  to big sur dmg url  instead , and remake a new fresh install ? 

Does anybody got the good Big Sur url ?

**Comment by arindas** [comment]
I don't have the keys and URL for Big Sur. I am however confused that the update didn't work as expected. Will look into this.

**Comment by arindas** [comment]
Here's how a different project solved it https://github.com/foxlet/macOS-Simple-KVM/issues/436#issuecomment-862703823

The proposed solution is to download https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/OpenCore.qcow2
and replace ESP.qcow2 with this. I will have to check and verify this myself. However, the only problem is I don't have a lot of internet balance to complete the update.

**Comment by tombombadilom** [comment]
```
[root@tomPC mac-on-linux-with-qemu]# wget https://github.com/kholia/OSX-KVM/raw/master/OpenCore-Catalina/OpenCore.qcow2
[root@tomPC mac-on-linux-with-qemu]# ./launch-macos.sh
qemu-system-x86_64: -drive id=OpenCore,if=virtio,format=qcow2,file=OpenCore.qcow2: Image is not in qcow2 format
```

**Comment by arindas** [comment]
Ummm just do this:
```bash
git restore .
git checkout -b test-branch
wget https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Catalina/OpenCore.qcow2
cp OpenCore.qcow2 ESP.qcow2
./launch-macos.sh
```

**Comment by arindas** [comment]
In any case, I did the above I'm downloading the security update right now. I Will post updates.

![2021-08-25-14:32:29-screenshot](https://user-images.githubusercontent.com/24752267/130761838-a90733c6-73e0-457e-9faf-a93f23344e66.png)

**Comment by tombombadilom** [comment]
[root@tomPC mac-on-linux-with-qemu]# cp OpenCore.qcow2 ESP.qcow2
[root@tomPC mac-on-linux-with-qemu]# ./launch-macos.sh
qemu-system-x86_64: -drive if=pflash,format=raw,readonly,file=packaged-firmware/OVMF_CODE.fd: warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
qemu-system-x86_64: -drive id=ESP,if=virtio,format=qcow2,file=ESP.qcow2: Image is not in qcow2 format
[root@tomPC mac-on-linux-with-qemu]# qemu-img info OpenCore.qcow2
image: OpenCore.qcow2
file format: raw
virtual size: 16.1 MiB (16842752 bytes)
disk size: 16.1 MiB

**Comment by arindas** [comment]
Ok I realize the problem.

Download using 
```
wget https://github.com/kholia/OSX-KVM/raw/master/OpenCore-Catalina/OpenCore.qcow2 -O ESP.qcow2
```

The other URL downloads a HTML page.

**Comment by tombombadilom** [comment]
```
[root@tomPC mac-on-linux-with-qemu]# qemu-img info ESP.qcow2
image: ESP.qcow2
file format: qcow2
virtual size: 384 MiB (402653184 bytes)
disk size: 16.1 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
[root@tomPC mac-on-linux-with-qemu]# ./launch-macos.sh
qemu-system-x86_64: -drive if=pflash,format=raw,readonly,file=packaged-firmware/OVMF_CODE.fd: warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
pulseaudio: pa_context_connect() failed
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver
audio: warning: Using timer based audio emulation
Authorization required, but no authorization protocol specified
Could not initialize SDL(x11 not available) - exitin
```

**Comment by tombombadilom** [comment]
## cannot launch mac os in root 
i have chowned ESP.qcow2 to my user and now it launch !

**Comment by tombombadilom** [comment]
# Big Sur Upgrade Complete !
![photo_2021-08-25_06-30-37](https://user-images.githubusercontent.com/1358803/130771921-1052d0fe-41d2-446c-b35a-9e3329ec1c06.jpg)

**Comment by arindas** [comment]
Thank you @tombombadilom for your help.
