### ISSUE TITLE
Check if dmg is downloaded instead of img

### ISSUE THREAD

**Issue by devcroc** [arindas/mac-on-linux-with-qemu#16]
In case, like me, you missed the `dmg2img` requirement, you have to re-download completely `BaseSystem.dmg` on the next run.

Perhaps check for requirements at the beginning of the script or check for the dmg image  instead of img to avoid redownloading to same ressource ?

**Comment by arindas** [comment]
The files are saved to the disk, so you may simply run dmg2img yourself without re-downloading. However, I do agree that I need to check for dependencies before executing the script.

**Comment by arindas** [comment]
@devcroc Mind reviewing the PR once?
