### ISSUE TITLE
Freeze on Big Sur using the new ESP.qcow2 resolved 

### ISSUE THREAD

**Issue by tombombadilom** [arindas/mac-on-linux-with-qemu#21]
Freeze happend after a long time of unused. I first thought it was a suspend problem and deactivated all suspend:
* from monitor 
* from max os 
* from linux 

But the problem remains...
I've got no error log in Mac os X 
and for qemu juste a tiny :
```
qemu : Slirp: Failed to send packet, ret: -1
```
To let you know there this issue https://github.com/foxlet/macOS-Simple-KVM/issues/499
I found this very helpfull https://support.apple.com/en-en/guide/mac-help/mchlp1168/mac
I just had to stop hard drive suspend to solve the problem

**Comment by notAperson939** [comment]
@tombombadilom How do you stop hard drive suspension?

**Comment by notAperson939** [comment]
@tombombadilom also, mine freezes during big sur installation in disk utility

**Comment by tombombadilom** [comment]
@notAperson939 hard rive suspspension is in the preference panel of your mac os x system , see energy saving , need to be deactvated before upgrading to big sur or monterrey.
have a look here https://support.apple.com/en-en/guide/mac-help/mchlp1168/mac
>> also, mine freezes during big sur installation in disk utility:  I don't get it , drive utility is intended to partition your disk not to install or  upgrade big sur

**Comment by notAperson939** [comment]
@tombombadilom It randomly freezes while i am using the computer and interacting with it.
