### ISSUE TITLE
Cannot install, no disk found

### ISSUE THREAD

**Issue by Olivier34** [arindas/mac-on-linux-with-qemu#23]
Hi,

When the message "Select the disk where you want to install macOS" is displayed, there is no available disk.

There is only one disk "macOS Base System" which is greyed. Cannont continue.

OS : Ubuntu 20.04.3 LTS

![Capture du 2021-09-01 11-18-30](https://user-images.githubusercontent.com/754309/131646148-fb191c07-8177-4a5d-9e53-3dd4408982a4.png)

**Comment by erikhu** [comment]
@Olivier34 i have the same problem

**Comment by arindas** [comment]
You have to format the virtual disk first. Only then will ot show up as an installation target.
Looks around a bit and you will find a disk menu. 
Setup a new partition there in the unallocated space.
