### ISSUE TITLE
Impossible to initialize MacOS system disk

### ISSUE THREAD

**Issue by j75** [arindas/mac-on-linux-with-qemu#36]
On Ubuntu 22.04 I have the the following issues when running `install-macos.sh`
- either the script is stuck displaying `vm_swap_create_file failed`
![install-macos-2022-10-30_18-31](https://user-images.githubusercontent.com/1899106/198893229-85e805d5-e7aa-4679-b93c-a67c77482e88.png)
- or, if somehow I manage to overcome that and I enter in the menu shown at https://github.com/popey/sosumi-snap, then selecting **Disk utility**  the macos.qcow2 is represented as a CD-ROM that cannot be partitioned etc...
- 
![Disk_Utility-2022-10-30_18-19](https://user-images.githubusercontent.com/1899106/198893312-0eb79c1b-7322-4007-8d2c-36d0f9088e53.png)

**Comment by tombombadilom** [comment]
you have first to partition the bigest disk named Apple Disk Virtio Block 
then install mac os on that disk
