### ISSUE TITLE
install-macos.sh: not found

### ISSUE THREAD

**Issue by replicajune** [arindas/mac-on-linux-with-qemu#4]
Hello,

I'm testing this as we speak. I had to adapt the run.sh script to change:

``` sh
exec install-macos.sh
```

to:

``` sh
exec "${PWD}/install-macos.sh"
```

As I faced the following issue using the exec command currently in the run.sh script :

> ./run.sh: line 31: exec: install-macos.sh: not found

Oddly enough, the previous exec command runs fine, so it's not quite clear why that one failed. I would however suggest to apply this change to all other exec commands to explicitly use a full path rather than calling script and assuming the user is in the root of the repo.

---

ps: I'm trying to see if mac would be a fit for me, having a vm would help so thanks a lot for this project :) !

**Comment by arindas** [comment]
Sorry you had to face this issue. I had used exec with incorrect syntax.

This commit resolves this: https://github.com/arindas/mac-on-linux-with-qemu/commit/fb1725b8703e405074134079ac226e7685bb99e7

I'm glad that this project was of use to you.

I'm closing this issue for now. Please re-open if the issue persists or re-open a new issue if any new problem occurs.

Thank you.
