### ISSUE TITLE
qemu-system-x86_64: Display 'sdl' is not available.

### ISSUE THREAD

**Issue by vernichon** [arindas/mac-on-linux-with-qemu#5]
Hi,

I have tried to launch the script but I have the following error
*** Checking for firmware files
*** Checking for Base System files
*** Checking for disk image
*** Check if installer has been run
*** Looks like the install hasn't been done yet, lets install
*** Install!
qemu-system-x86_64: Display 'sdl' is not available.

Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

**Comment by florianroulet** [comment]
Same here with ubuntu 21.04

**Comment by arindas** [comment]
This seems to be an issue with the qemu package on ubuntu and related distributions: https://askubuntu.com/questions/1322423/qemu-system-x86-64-display-sdl-is-not-available

Try replacing the `-display sdl,gl=on` options with `-display gtk,gl=off`. Although I'm not sure if it will work.
