### ISSUE TITLE
Disk not found during install

### ISSUE THREAD

**Issue by Yamakaky** [arindas/mac-on-linux-with-qemu#7]
I'm trying a fresh install. I can launch the installer, accept the license, but then there is only the disk "macOS base system" (2Go) marked "this disk is locked", and no other disk. I tried to delete all the files and restart, same result. Am I missing something?

No error message in the logs.

Nice work that I can get to this point!

**Comment by Yamakaky** [comment]
I managed to do it by identifying the 64Go disk in the disk manager and format it. Could it be automated from bash? Maybe create the partition table?

**Comment by arindas** [comment]
Will have to look into the automation aspect. Since you have solved this for yourself I am closing the issue.
