### ISSUE TITLE
Question on resolution

### ISSUE THREAD

**Issue by flaviencrochard** [arindas/mac-on-linux-with-qemu#9]
Hello,
I wonder if i could get the same resolution as you have on the screenshot. In the settings of the virtual machine, i only get 1280x720, do you have any clue if i can get higher resolution ?
Thanks
![Capture du 22-08-2021 21:21:18](https://user-images.githubusercontent.com/564388/130367498-a3371d4b-82d9-4808-a039-02ea2f4edae5.png)

**Comment by arindas** [comment]
![2021-08-23-11:12:03-screenshot](https://user-images.githubusercontent.com/24752267/130396374-aba60c4a-5085-4b69-af21-db7f5f7b34c2.png)

It's the same for me. I use i3wm which probably scales it up.

**Comment by arindas** [comment]
I don't know how to increase the resolution, to be honest. I will need to research a bit

**Comment by arindas** [comment]
You should be able to access higher resolutions now.

Reference: https://superuser.com/questions/132322/how-to-increase-the-visualized-screen-resolution-on-qemu-kvm

**Comment by flaviencrochard** [comment]
Perfect ! Thanks you :)
